# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: DoubleSpeak Magazine
email: staff@doublespeakmagazine.org
description: >- # this means to ignore newlines until "baseurl:"
  DoubleSpeak is the University of Pennsylvania’s only journal for literary translation and the only literary translation journal in the country run by undergraduate students. Founded over a decade ago, our annual journal celebrates a range of languages, cultures, and countries through thoughtful curation of poets across centuries and around the world.
baseurl: "/doublespeak" # the subpath of your site, e.g. /blog
url: "https://chradil.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 


# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

collections:

  #used to generate the tags for the site
  author_tags:
    layout: 'tagpage'
    output: true # this must be true for your .md pages to be built to html!
    metadata:
      source: 'authors.csv' # path to the metadata file, must be within '_data'
    images:
      source: 'source_images/objects' # path to the directory of source images, must be within '_data'

  language_tags:
    layout: 'tagpage'
    output: true # this must be true for your .md pages to be built to html!
    metadata:
      source: 'languages.csv' # path to the metadata file, must be within '_data'
    images:
      source: 'source_images/objects' # path to the directory of source images, must be within '_data'

  translator_tags:
    layout: 'tagpage'
    output: true # this must be true for your .md pages to be built to html!
    metadata:
      source: 'translators.csv' # path to the metadata file, must be within '_data'
    images:
      source: 'source_images/objects' # path to the directory of source images, must be within '_data'

  #used to generate the poem + note pages for each issue/year
  poems_2022:
    layout: 'poempage'
    output: true # this must be true for your .md pages to be built to html!
    metadata:
      source: 'poems_2022.csv' # path to the metadata file, must be within '_data'
    images:
      source: 'source_images/objects' # path to the directory of source images, must be within '_data'
  notes_2022:
    layout: 'notepage'
    output: true # this must be true for your .md pages to be built to html!
    metadata:
      source: 'poems_2022.csv' # path to the metadata file, must be within '_data'
    images:
      source: 'source_images/objects' # path to the directory of source images, must be within '_data'
  
  poems_2021:
    layout: 'poempage'
    output: true # this must be true for your .md pages to be built to html!
    metadata:
      source: 'poems_2021.csv' # path to the metadata file, must be within '_data'
    images:
      source: 'source_images/objects' # path to the directory of source images, must be within '_data'
  notes_2021:
    layout: 'notepage'
    output: true # this must be true for your .md pages to be built to html!
    metadata:
      source: 'poems_2021.csv' # path to the metadata file, must be within '_data'
    images:
      source: 'source_images/objects' # path to the directory of source images, must be within '_data'

  poems_2020:
    layout: 'poempage'
    output: true # this must be true for your .md pages to be built to html!
    metadata:
      source: 'poems_2020.csv' # path to the metadata file, must be within '_data'
    images:
      source: 'source_images/objects' # path to the directory of source images, must be within '_data'
  notes_2020:
    layout: 'notepage'
    output: true # this must be true for your .md pages to be built to html!
    metadata:
      source: 'poems_2020.csv' # path to the metadata file, must be within '_data'
    images:
      source: 'source_images/objects' # path to the directory of source images, must be within '_data'
  
  poems_2019:
    layout: 'poempage'
    output: true # this must be true for your .md pages to be built to html!
    metadata:
      source: 'poems_2019.csv' # path to the metadata file, must be within '_data'
    images:
      source: 'source_images/objects' # path to the directory of source images, must be within '_data'
  notes_2019:
    layout: 'notepage'
    output: true # this must be true for your .md pages to be built to html!
    metadata:
      source: 'poems_2019.csv' # path to the metadata file, must be within '_data'
    images:
      source: 'source_images/objects' # path to the directory of source images, must be within '_data'

  poems_2018:
    layout: 'poempage'
    output: true # this must be true for your .md pages to be built to html!
    metadata:
      source: 'poems_2018.csv' # path to the metadata file, must be within '_data'
    images:
      source: 'source_images/objects' # path to the directory of source images, must be within '_data'
  notes_2018:
    layout: 'notepage'
    output: true # this must be true for your .md pages to be built to html!
    metadata:
      source: 'poems_2018.csv' # path to the metadata file, must be within '_data'
    images:
      source: 'source_images/objects' # path to the directory of source images, must be within '_data'
  
  poems_2017:
    layout: 'poempage'
    output: true # this must be true for your .md pages to be built to html!
    metadata:
      source: 'poems_2017.csv' # path to the metadata file, must be within '_data'
    images:
      source: 'source_images/objects' # path to the directory of source images, must be within '_data'
  notes_2017:
    layout: 'notepage'
    output: true # this must be true for your .md pages to be built to html!
    metadata:
      source: 'poems_2017.csv' # path to the metadata file, must be within '_data'
    images:
      source: 'source_images/objects' # path to the directory of source images, must be within '_data'

  poems_2016:
    layout: 'poempage'
    output: true # this must be true for your .md pages to be built to html!
    metadata:
      source: 'poems_2016.csv' # path to the metadata file, must be within '_data'
    images:
      source: 'source_images/objects' # path to the directory of source images, must be within '_data'
  notes_2016:
    layout: 'notepage'
    output: true # this must be true for your .md pages to be built to html!
    metadata:
      source: 'poems_2016.csv' # path to the metadata file, must be within '_data'
    images:
      source: 'source_images/objects' # path to the directory of source images, must be within '_data'

#used to generate the search function across all years of content
search:
  main:
    index: '/search/index.json' # file the index will get written to
    collections:
      poems_2022:
        content: true # whether or not to index page content
        fields: # the metadata fields to index
          - transtitle
          - title
          - author
          - translator
          - poem
          - transpoem
          - language
      poems_2021:
        content: true # whether or not to index page content
        fields: # the metadata fields to index
          - transtitle
          - title
          - author
          - translator
          - poem
          - transpoem
          - language
      poems_2020:
        content: true # whether or not to index page content
        fields: # the metadata fields to index
          - transtitle
          - title
          - author
          - translator
          - poem
          - transpoem
          - language
      poems_2019:
        content: true # whether or not to index page content
        fields: # the metadata fields to index
          - transtitle
          - title
          - author
          - translator
          - poem
          - transpoem
          - language
      poems_2018:
        content: false # whether or not to index page content
        fields: # the metadata fields to index
          - transtitle
          - title
          - author
          - translator
          - poem
          - transpoem
          - language
      poems_2017:
        content: false # whether or not to index page content
        fields: # the metadata fields to index
          - transtitle
          - title
          - author
          - translator
          - poem
          - transpoem
          - language
      poems_2016:
        content: false # whether or not to index page content
        fields: # the metadata fields to index
          - transtitle
          - title
          - author
          - translator
          - poem
          - transpoem
          - language