# run bundle exec rake wax:pages collection_name
# run bundle exec rake wax:pages collection_name

# run bundle exec rake wax:search main
# run bundle exec jekyll build

name: Rebuild + deploy site on push

on:
  push:
    branches: [$default-branch]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        # uses: ruby/setup-ruby@8575951200e472d5f2d95c625da0c7bec8217c42 # v1.161.0
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4
      # - name: get wax
      #   run: git clone https://github.com/minicomp/wax.git
      # - name: cd + install gems
      #   run:  cd wax && bundle install 
        ## here begin the collection builds
      - name: build author tags
        run: bundle exec rake wax:pages author_tags
      - name: clobber poems 2023
        run: bundle exec rake wax:clobber poems_2023
      - name: build poems 2023
        run: bundle exec rake wax:pages poems_2023
      - name: clobber poems 2022
        run: bundle exec rake wax:clobber poems_2022
      - name: Build with Jekyll
        # Outputs to the './_site' directory by default
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production
      - name: Upload artifact
        # Automatically uploads an artifact from the './_site' directory by default
        uses: actions/upload-pages-artifact@v3

    # Deployment job
  deploy:
    environment:
      name: github-pages
      url: https://www.doublespeakmagazine.org
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4



